"""Add match and match_preference tables, and update fitness_profiles

Revision ID: 027de9d9b174
Revises: 29c71e887492
Create Date: 2026-01-24 21:05:13.195004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '027de9d9b174'
down_revision: Union[str, Sequence[str], None] = '29c71e887492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('gender_preference', sa.String(length=20), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=False),
    sa.Column('max_distance_km', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_preferences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('matches',
    sa.Column('user_a_id', sa.String(length=36), nullable=False),
    sa.Column('user_b_id', sa.String(length=36), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sqlite.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a_id', 'user_b_id', name='unique_match_pair')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_overall_score'), ['overall_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_user_a_id'), ['user_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_user_b_id'), ['user_b_id'], unique=False)

    with op.batch_alter_table('fitness_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_profiles', schema=None) as batch_op:
        batch_op.drop_column('age')
        batch_op.drop_column('gender')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_user_b_id'))
        batch_op.drop_index(batch_op.f('ix_matches_user_a_id'))
        batch_op.drop_index(batch_op.f('ix_matches_status'))
        batch_op.drop_index(batch_op.f('ix_matches_overall_score'))
        batch_op.drop_index(batch_op.f('ix_matches_id'))

    op.drop_table('matches')
    with op.batch_alter_table('match_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_match_preferences_id'))

    op.drop_table('match_preferences')
    # ### end Alembic commands ###
