"""Initial migration - create users, fitness_profiles, gyms tables

Revision ID: 29c71e887492
Revises: 
Create Date: 2026-01-18 19:08:31.856904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '29c71e887492'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gyms',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gyms_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_gyms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gyms_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('fitness_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('fitness_level', sa.String(length=20), nullable=False),
    sa.Column('goals', sqlite.JSON(), nullable=False),
    sa.Column('workout_types', sqlite.JSON(), nullable=False),
    sa.Column('preferred_schedule', sa.String(length=20), nullable=False),
    sa.Column('preferred_days', sqlite.JSON(), nullable=False),
    sa.Column('preferred_gym_id', sa.String(length=36), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['preferred_gym_id'], ['gyms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fitness_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fitness_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fitness_profiles_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fitness_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_fitness_profiles_id'))

    op.drop_table('fitness_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gyms_name'))
        batch_op.drop_index(batch_op.f('ix_gyms_id'))
        batch_op.drop_index(batch_op.f('ix_gyms_city'))

    op.drop_table('gyms')
    # ### end Alembic commands ###
