"""Add user_stats table

Revision ID: c03d0b0c774f
Revises: ac6d5987c05d
Create Date: 2026-01-26 22:26:26.483038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03d0b0c774f'
down_revision: Union[str, Sequence[str], None] = 'ac6d5987c05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stats',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('total_workouts', sa.Integer(), nullable=False),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_calories_burned', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_workout_date', sa.Date(), nullable=True),
    sa.Column('total_matches', sa.Integer(), nullable=False),
    sa.Column('active_partners', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_stats_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_stats_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_stats_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_stats_id'))

    op.drop_table('user_stats')
    # ### end Alembic commands ###
